---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "live"
    allow:
      - dependency-type: "all"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "live"
    allow:
      - dependency-type: "all"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "live"
    allow:
      - dependency-type: "all"
