---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore: 
      - dependency-name: "*"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    labels: []
    ignore: 
      - dependency-name: "*"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
    ignore: 
      - dependency-name: "*"